/*
 * This package contains filters used for intercepting HTTP requests and responses
 * in the API layer.
 */
package com.api.filter;

import jakarta.ws.rs.container.*;
import jakarta.ws.rs.ext.Provider;

import java.io.IOException;
import java.util.logging.Logger;

/**
 * LoggingFilter is a JAX-RS filter that logs incoming HTTP requests
 * and outgoing HTTP responses.
 * 
 * It implements:
 * - ContainerRequestFilter  → to intercept and log incoming requests
 * - ContainerResponseFilter → to intercept and log outgoing responses
 */
@Provider // Marks this class as a provider so JAX-RS runtime can detect and register it automatically
public class LoggingFilter implements ContainerRequestFilter, ContainerResponseFilter {

    // Logger instance used to log request and response details
    private static final Logger logger = Logger.getLogger(LoggingFilter.class.getName());

    /**
     * This method is triggered before the request reaches the resource (API endpoint).
     * It logs the HTTP method (GET, POST, etc.) and the requested path.
     *
     * @param requestContext contains request-specific information
     * @throws IOException if an input/output error occurs
     */
    @Override
    public void filter(ContainerRequestContext requestContext) throws IOException {
        logger.info("REQUEST → " 
                + requestContext.getMethod() + " " 
                + requestContext.getUriInfo().getPath());
    }

    /**
     * This method is triggered after the response is generated by the resource.
     * It logs the HTTP response status code (e.g., 200, 404, 500).
     *
     * @param requestContext  contains request-specific information
     * @param responseContext contains response-specific information
     * @throws IOException if an input/output error occurs
     */
    @Override
    public void filter(ContainerRequestContext requestContext,
                       ContainerResponseContext responseContext) throws IOException {
        logger.info("RESPONSE → " + responseContext.getStatus());
    }
}